<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="http://model/1.0" nsPrefix="model">
  <eClassifiers xsi:type="ecore:EClass" name="MetaFile" eSuperTypes="#//MetaDocument">
    <eStructuralFeatures xsi:type="ecore:EReference" name="versions" upperBound="-1"
        eType="#//Version"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Version">
    <eStructuralFeatures xsi:type="ecore:EReference" name="chunks" upperBound="-1"
        eType="#//Chunk"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="counter" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Permission">
    <eLiterals name="READONLY"/>
    <eLiterals name="WRITE" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserPermission">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userid" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="permission" lowerBound="1"
        eType="#//Permission" defaultValueLiteral="permission"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MetaDocument" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="#//PublicKey"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="PublicKey" instanceClassName="java.security.PublicKey"/>
  <eClassifiers xsi:type="ecore:EDataType" name="PrivateKey" instanceClassName="java.security.PrivateKey"/>
  <eClassifiers xsi:type="ecore:EDataType" name="KeyPair" instanceClassName="java.security.KeyPair"/>
  <eClassifiers xsi:type="ecore:EClass" name="MetaFolder" eSuperTypes="#//MetaDocument">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" upperBound="-1"
        eType="#//MetaDocument"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="userPermission" upperBound="-1"
        eType="#//UserPermission"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Chunk">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="data" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteArray"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserProfile">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fileTree" lowerBound="1"
        eType="#//FileTree"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="signatureKeys" lowerBound="1"
        eType="#//KeyPair"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FileTree">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//FileTreeNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FileTreeNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="keyPair" lowerBound="1"
        eType="#//KeyPair"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="domainKey" eType="#//PrivateKey"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//FileTree"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OnlinePeer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PeerAddress" upperBound="-1"
        eType="#//PeerAddress"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="master" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Locations">
    <eStructuralFeatures xsi:type="ecore:EReference" name="onlinePeers" eType="#//OnlinePeer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="PeerAddress" instanceClassName="net.tomp2p.peers.PeerAddress"/>
</ecore:EPackage>
